[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.4",
    "pydantic>=2.12.3",
    "sqlalchemy>=2.0.44",
    "starlette>=0.49.1",
    "uvicorn>=0.38.0",
]
